macro(check_debian _isdebian)
    set(osrelease_path "/etc/os-release")
    if (EXISTS ${osrelease_path})
        file(READ ${osrelease_path} OS_RELEASE)
        string(FIND "${OS_RELEASE}" "debian" _isdebian)
        if(_isdebian EQUAL -1)
            set(${_isdebian} OFF)
        else()
            set(PRETTY_NAME)
            set(${_isdebian} ON)

            # Get the dist and print
            string(REGEX MATCH "PRETTY_NAME=\"([^\"]+)\"" PRETTY_NAME_MATCH "${OS_RELEASE}")
            if(PRETTY_NAME_MATCH)
                string(REGEX REPLACE "PRETTY_NAME=\"([^\"]+)\"" "\\1" PRETTY_NAME "${PRETTY_NAME_MATCH}")
            else()
                set(PRETTY_NAME "")
            endif()
            message("-- Using Debian ${PRETTY_NAME}")
        endif()
    else()
        set(_isdebian OFF)
    endif()
endmacro()